spring.application.name: User Service

# server configuration
server:
   port: 8080
   #servlet.contextPath: /user-service

# mongoDB configuration
spring.data.mongodb:
   database: demo
   host: ${MONGO_HOST:localhost}
   port: 27017
   autoIndexCreation: true